# Generated by Django 5.2.7 on 2026-07-21 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Espacios',
            new_name='Espacio',
        ),
    ]
