# Generated by Django 5.2.7 on 2026-07-21 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_reserva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='hora_final',
            new_name='hora_fin',
        ),
    ]
